language: python

sudo: required
services:
  - docker

env:
  - PYTHON=2.7
  - PYTHON=3.5

# Setup anaconda
install:
  #  Disabled since docker pull does not affect cache
  #  Fixed in Docker 1.13 with --cache-from
  #  - docker pull befelix/lyapunov-learning-private:${PYTHON} || true
  - docker build -f Dockerfile --build-arg PYTHON=${PYTHON} -t test-image .
  - docker ps -a

# Run tests
script:
  - docker run test-image flake8 safeopt --exclude "test*.py,__init__.py" --ignore=E402,E731,W503,E741 --show-source
  - docker run test-image flake8 safeopt --filename="__init__.py,test*.py" --ignore=F,E402,W503 --show-source
  - docker run test-image pydocstyle safeopt --convention=numpy
  - docker run test-image pytest --doctest-modules --cov --cov-fail-under=50 safeopt

